### Get all users
GET http://127.0.0.1:8000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndlZXB1bEBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImZpcnN0X25hbWUiOiJ3ZWVwdWwiLCJsYXN0X25hbWUiOiJnaGFkaSIsImV4cCI6MTc2MTc0NzYyNn0.HgpkSCkwXCSpgli8Jn6Ufsxdij-ea1AFVR-lA3xvVPo